# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml
build:
  excludeCorrectable: true

formatting:
  Indentation:
    continuationIndentSize: 8
  ParameterListWrapping:
    indentSize: 8
  NoWildcardImports:
    active: false
  MultiLineIfElse:
    active: false

style:
  NewLineAtEndOfFile:
    active: false
  WildcardImport:
    active: false
